org: alexandriax
service: meet-auth-server

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  timeout: 30

  environment:
    NODE_ENV: ${env:NODE_ENV, 'development'}
    GOOGLE_API_KEY: ${env:GOOGLE_API_KEY, 'api'}
    CLIENT_ID: ${file(config.json):CLIENT_ID}
    CLIENT_SECRET: ${file(config.json):CLIENT_SECRET}
    CALENDAR_ID: ${file(config.json):CALENDAR_ID}

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
        - s3:*
        - sns:*
        - sqs:*
      Resource: "*"

functions:
  getAuthURL:
    handler: handler.getAuthURL
    layers:
      - { Ref: GoogleapisLayerLambdaLayer }
    events:
      - http:
          path: api/get-auth-url
          method: get
  getAccessToken:
    handler: handler.getAccessToken
    layers:
      - { Ref: GoogleapisLayerLambdaLayer }
    events:
      - http:
          path: api/token/{code}
          method: get
  getCalendarEvents:
    handler: handler.getCalendarEvents
    layers:
      - { Ref: GoogleapisLayerLambdaLayer}
    events:
      - http: 
          path: api/get-events/{access_token}
          method: get

plugins:
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 3000

layers:
  googleapisLayer:
    path: layer
    compatibleRuntimes:
      - nodejs18.x

package:
  individually: true
  exclude:
    - node_modules/**
    #- .git/**
    #- .serverless/**
    #- '*.md'
    #- '*.json'

# chatgpt code (command not working)